
[workspace]
resolver = "2"
members = [
    # -- Tools
    "crates/tools/gen-key",
    # -- Application Libraries
    "crates/libs/lib-base",
    # e.g., model, ctx, config, pwd, token.
    "crates/libs/lib-core",
    # -- Application Services
    "crates/services/web-server",
]
