


[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG = "web_server=debug,lib_core=debug,lib_base=debug"

# -- Service Environment Variables
# IMPORTANT:
#    For cargo commands only.

## -- Secrets
# Kyes and passwords below are for localhost dev ONLY.
# e.g., "password" type of passwords.
# i.e., Encryption not need.
SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"

SERVICE_PWD_KEY = "CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA"

SERVICE_TOKEN_KEY = "9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw"
SERVICE_TOKEN_DURATION_SEC = "1800"                                                                          # 30 minutes

## -- CofnigMap

# This will be relative to Cargo.toml
SERVICE_WEB_FOLDER = "web-folder/"
