


[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG = "axum_web_dev=debug"

# -- Service Environment Variables
# IMPORTANT:
#    For cargo commands only.

## -- Secrets
# Kyes and passwords below are for localhost dev ONLY.
# e.g., "password" type of passwords.
# i.e., Encryption not need.
SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@localhost/app_db"

## -- CofnigMap

# This will be relative to Cargo.toml
SERVICE_WEB_FOLDER = "web-folder/"
