


[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG = "axum_web_dev=debug"

# -- Service Environment Variables
# IMPORTANT:
#    For cargo commands only.

## -- CofnigMap

# This will be relative to Cargo.toml
SERVICE_WEB_FOLDER = "web-folder/"
